server:
  port: 80

spring:
  application:
    name: service-gateway

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          - id: service-video
            uri: lb://service-video
            predicates:
              - Path=/*/publish/**,/*/feed/**
          - id: service-user
            uri: lb://service-user
            predicates:
              - Path=/*/user/**
          - id: service-oss
            uri: lb://service-oss
            predicates:
              - Path=/*/oss/**